name: timothyeyrichphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#4f4f4f'
    - '#e7e7e7'
    - '#787878'
    - '#afafaf'
  brandStrength: 0.5691191488876939
  lightness: 0.488386495038867
  saturation: 0.19490307080559433
  rhythmicContrast: 0.5532424433622509
purpose: []
